### ISSUE TITLE
WSL Install instructions

### ISSUE THREAD

**Issue by michaeltreat** [codefellows/code-401-dotnet-prework#1]
Currently no WSL install instructions.

@Aiverson1011 Here is my completed doc for the WSL install instructions. I know you had mentioned a couple different approaches, but here is mine. Please let me know what you think!

https://github.com/michaeltreat/Windows-Subsystem-For-Linux-Setup

**Comment by michaeltreat** [comment]
Not sure if that guide will be super useful for .NET, but the first two pages will help at least get it installed. The workflow for .NET users may be different that what the guide describes.

**Comment by brookr** [comment]
Closed in favor of creating .NET specific setup instructions in the /setup-guide repo.
