### ISSUE TITLE
Broken link in Canvas

### ISSUE THREAD

**Issue by brookr** [codefellows/code-401-dotnet-prework#5]
Needs to be fixed in:

401d8: https://canvas.instructure.com/courses/1618204/assignments/11470901 
Template: https://canvas.instructure.com/courses/1411331/assignments/9495687

**Comment by brookr** [comment]
Should also be content iframed from GitHub, so it can be updated everywhere at once.

**Comment by Aiverson1011** [comment]
fixed in tempalte
