### ISSUE TITLE
Migrate assignments to draw from common, or from main guide repo

### ISSUE THREAD

**Issue by brookr** [codefellows/code-401-dotnet-prework#6]
See assignments in: https://github.com/codefellows/common_curriculum/tree/master/prep_work

**Comment by brookr** [comment]
Be sure Prework includes the Status Report assignment:

https://codefellows.github.io/common_curriculum/career_coaching/401/status-report

**Comment by brookr** [comment]
Migrate computer setup assignment to the /setup-guide repo.

**Comment by brookr** [comment]
@johncokos Are all the issues described above resolved?

**Comment by johncokos** [comment]
All completed.
